// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7eWschJ9SCYdJDtgpqxIhnjMEztJpA8E',
    appId: '1:28356929587:web:aec5caa362d55ac2779b46',
    messagingSenderId: '28356929587',
    projectId: 'chrono-f7c8b',
    authDomain: 'chrono-f7c8b.firebaseapp.com',
    storageBucket: 'chrono-f7c8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1RyE7kmqGZfWgluyB3r6o22GfZkhGrA',
    appId: '1:28356929587:android:d2acd13c967636e2779b46',
    messagingSenderId: '28356929587',
    projectId: 'chrono-f7c8b',
    storageBucket: 'chrono-f7c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyDlzjE9sZjAzpHVi6lBCZvqzVHk2-aH4',
    appId: '1:28356929587:ios:48cf7934793f7485779b46',
    messagingSenderId: '28356929587',
    projectId: 'chrono-f7c8b',
    storageBucket: 'chrono-f7c8b.appspot.com',
    iosClientId: '28356929587-1a6ss1sihp4msh9pv07agp5fu87v842h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chrono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyDlzjE9sZjAzpHVi6lBCZvqzVHk2-aH4',
    appId: '1:28356929587:ios:48cf7934793f7485779b46',
    messagingSenderId: '28356929587',
    projectId: 'chrono-f7c8b',
    storageBucket: 'chrono-f7c8b.appspot.com',
    iosClientId: '28356929587-1a6ss1sihp4msh9pv07agp5fu87v842h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chrono',
  );
}
